import type { Metadata } from 'next'
import { Elms_Sans } from 'next/font/google'
import { Provider } from '@/components/ui/provider'
import './global.css'

const elmsSans = Elms_Sans({
  style: ['normal', 'italic'],
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning={true}>
      <body className={`${elmsSans.className} `}>
        <Provider themes={['light']}>{children}</Provider>
      </body>
    </html>
  )
}
